"""init

Revision ID: 105afcb393f8
Revises: 
Create Date: 2026-05-29 23:44:35.645940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '105afcb393f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('film_settings')
    op.drop_index(op.f('idx_plot_points_novel'), table_name='plot_points')
    op.drop_table('plot_points')
    op.drop_index(op.f('idx_cost_novel'), table_name='cost_ledger')
    op.drop_table('cost_ledger')
    op.drop_table('scheduler_state')
    op.drop_table('chapter_fts_config')
    op.drop_table('visual_characters')
    op.drop_index(op.f('idx_run_logs_novel'), table_name='run_logs')
    op.drop_index(op.f('idx_run_logs_time'), table_name='run_logs')
    op.drop_table('run_logs')
    op.drop_table('chapter_fts_docsize')
    op.drop_index(op.f('idx_voice_novel'), table_name='voice_profile')
    op.drop_table('voice_profile')
    op.drop_table('audio_stats')
    op.drop_index(op.f('idx_consistency_novel'), table_name='consistency_log')
    op.drop_table('consistency_log')
    op.drop_index(op.f('idx_world_evo_novel'), table_name='world_evolution')
    op.drop_table('world_evolution')
    op.drop_table('chapter_fts_data')
    op.drop_table('audio_playlist')
    op.drop_index(op.f('idx_embeddings_chapter'), table_name='chapter_embeddings')
    op.drop_table('chapter_embeddings')
    op.drop_index(op.f('idx_location_novel'), table_name='location_history')
    op.drop_table('location_history')
    op.drop_table('novel_tags')
    op.drop_index(op.f('idx_unsaid_novel'), table_name='unsaid_book')
    op.drop_table('unsaid_book')
    op.drop_table('storyboards')
    op.drop_table('audio_bookmarks')
    op.drop_index(op.f('idx_chapter_summaries_novel'), table_name='chapter_summaries')
    op.drop_table('chapter_summaries')
    op.drop_index(op.f('idx_char_state_novel'), table_name='character_state')
    op.drop_table('character_state')
    op.drop_index(op.f('idx_subplots_novel'), table_name='subplots')
    op.drop_table('subplots')
    op.drop_table('character_voices')
    op.drop_index(op.f('idx_world_novel'), table_name='world_state')
    op.drop_table('world_state')
    op.drop_index(op.f('idx_timeline_novel'), table_name='story_timeline')
    op.drop_table('story_timeline')
    op.drop_table('chapter_fts_idx')
    op.drop_index(op.f('idx_foreshadowing_novel'), table_name='foreshadowing_tracker')
    op.drop_table('foreshadowing_tracker')
    op.drop_index(op.f('idx_perf_novel'), table_name='performance_logs')
    op.drop_table('performance_logs')
    op.drop_index(op.f('idx_publish_records_ch'), table_name='publish_records')
    op.drop_table('publish_records')
    op.drop_table('audio_settings')
    op.drop_index(op.f('idx_story_arcs_novel'), table_name='story_arcs')
    op.drop_table('story_arcs')
    op.drop_table('chapter_fts_content')
    op.drop_table('audio_progress')
    op.drop_table('platform_auth')
    op.drop_table('reanchor_snapshots')
    op.drop_table('chapter_fts')
    op.alter_column('chapter_drafts', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('chapter_drafts', 'chapter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chapter_drafts', 'preview',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('chapter_drafts', 'hook',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.drop_index(op.f('idx_drafts_chapter'), table_name='chapter_drafts')
    op.drop_constraint(None, 'chapter_drafts', type_='foreignkey')
    op.create_foreign_key(None, 'chapter_drafts', 'chapters', ['chapter_id'], ['id'], ondelete='CASCADE')
    op.alter_column('chapter_versions', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('chapter_versions', 'word_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('chapter_versions', 'version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('chapter_versions', 'reason',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('chapter_versions', 'created_at',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("(datetime('now'))"))
    op.drop_index(op.f('idx_chapter_versions'), table_name='chapter_versions')
    op.drop_constraint(None, 'chapter_versions', type_='foreignkey')
    op.create_foreign_key(None, 'chapter_versions', 'chapters', ['chapter_id'], ['id'], ondelete='CASCADE')
    op.alter_column('chapters', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('chapters', 'summary',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('chapters', 'content',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('chapters', 'ending_hook',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('chapters', 'key_events',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('chapters', 'revelations',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('chapters', 'quality_score',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('chapters', 'model_used',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('chapters', 'prompt_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('chapters', 'completion_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('chapters', 'cost',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('chapters', 'generation_duration_ms',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_chapters_novel'), table_name='chapters')
    op.drop_index(op.f('idx_chapters_published'), table_name='chapters')
    op.drop_constraint(None, 'chapters', type_='foreignkey')
    op.create_foreign_key(None, 'chapters', 'novels', ['novel_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chapters', 'edit_ratio')
    op.drop_column('chapters', 'intensity')
    op.drop_column('chapters', 'emotion')
    op.drop_column('chapters', 'chapter_type')
    op.drop_column('chapters', 'prompt_version')
    op.drop_column('chapters', 'plot_functions')
    op.drop_column('chapters', 'scene_count')
    op.drop_column('chapters', 'hook_type')
    op.drop_column('chapters', 'narrative_modes')
    op.add_column('character_relations', sa.Column('c1_name', sa.Text(), nullable=False))
    op.add_column('character_relations', sa.Column('c2_name', sa.Text(), nullable=False))
    op.add_column('character_relations', sa.Column('relation_type', sa.Text(), nullable=False))
    op.alter_column('character_relations', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_index(op.f('idx_relations_novel'), table_name='character_relations')
    op.create_unique_constraint(None, 'character_relations', ['novel_id', 'c1_name', 'c2_name'])
    op.drop_constraint(None, 'character_relations', type_='foreignkey')
    op.drop_constraint(None, 'character_relations', type_='foreignkey')
    op.drop_constraint(None, 'character_relations', type_='foreignkey')
    op.create_foreign_key(None, 'character_relations', 'novels', ['novel_id'], ['id'], ondelete='CASCADE')
    op.drop_column('character_relations', 'evolution_stages')
    op.drop_column('character_relations', 'key_moments')
    op.drop_column('character_relations', 'char_2_id')
    op.drop_column('character_relations', 'char_1_id')
    op.drop_column('character_relations', 'history')
    op.drop_column('character_relations', 'relation')
    op.drop_column('character_relations', 'description')
    op.alter_column('characters', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('characters', 'personality',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('characters', 'background',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('characters', 'power_level',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('characters', 'secrets',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
    op.drop_index(op.f('idx_characters_novel'), table_name='characters')
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.create_foreign_key(None, 'characters', 'novels', ['novel_id'], ['id'], ondelete='CASCADE')
    op.drop_column('characters', 'last_appearance')
    op.drop_column('characters', 'foil_target')
    op.drop_column('characters', 'foil_contrasting_trait')
    op.drop_column('characters', 'wound')
    op.drop_column('characters', 'death_impact')
    op.drop_column('characters', 'foil_type')
    op.drop_column('characters', 'arc')
    op.drop_column('characters', 'motivation')
    op.drop_column('characters', 'death_chapter')
    op.drop_column('characters', 'voice_profile_json')
    op.drop_column('characters', 'lifecycle_status')
    op.drop_column('characters', 'goal')
    op.drop_column('characters', 'foil_shared_trait')
    op.drop_column('characters', 'introduced_arc')
    op.alter_column('cost_logs', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('cost_logs', 'chapter_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cost_logs', 'prompt_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('cost_logs', 'completion_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('cost_logs', 'cost',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('cost_logs', 'created_at',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("(datetime('now'))"))
    op.drop_index(op.f('idx_cost_logs_novel'), table_name='cost_logs')
    op.drop_constraint(None, 'cost_logs', type_='foreignkey')
    op.create_foreign_key(None, 'cost_logs', 'novels', ['novel_id'], ['id'], ondelete='CASCADE')
    op.drop_column('cost_logs', 'duration_ms')
    op.drop_column('cost_logs', 'total_tokens')
    op.drop_column('cost_logs', 'purpose')
    op.alter_column('factions', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('factions', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('factions', 'leader',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('factions', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'factions', type_='foreignkey')
    op.create_foreign_key(None, 'factions', 'novels', ['novel_id'], ['id'], ondelete='CASCADE')
    op.drop_column('factions', 'internal_conflict')
    op.drop_column('factions', 'history')
    op.drop_column('factions', 'enemies')
    op.drop_column('factions', 'resources')
    op.drop_column('factions', 'allies')
    op.drop_column('factions', 'power_level')
    op.drop_column('factions', 'goal')
    op.alter_column('model_providers', 'id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('model_providers', 'updated_at')
    op.drop_column('model_providers', 'created_at')
    op.alter_column('novels', 'id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('novels', 'synopsis',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('novels', 'world_name',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('novels', 'world_era',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('novels', 'world_geo',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('novels', 'power_system',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('novels', 'world_rules',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('novels', 'main_arc',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('novels', 'current_arc',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'开篇'"))
    op.drop_column('novels', 'antagonist_system')
    op.drop_column('novels', 'information_plan')
    op.drop_column('novels', 'reader_model')
    op.drop_column('novels', 'narrative_template')
    op.drop_column('novels', 'sub_genres')
    op.drop_column('novels', 'theme')
    op.add_column('style_profiles', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('style_profiles', sa.Column('genre', sa.Text(), nullable=False))
    op.add_column('style_profiles', sa.Column('writer_voice', sa.Text(), nullable=False))
    op.add_column('style_profiles', sa.Column('emotional_budget', sa.Text(), nullable=False))
    op.add_column('style_profiles', sa.Column('rhythm_mode', sa.Text(), nullable=False))
    op.add_column('style_profiles', sa.Column('gap_rule', sa.Text(), nullable=False))
    op.add_column('style_profiles', sa.Column('central_question', sa.Text(), nullable=False))
    op.add_column('style_profiles', sa.Column('soul_statement', sa.Text(), nullable=False))
    op.add_column('style_profiles', sa.Column('target_platform', sa.Text(), nullable=False))
    op.alter_column('style_profiles', 'novel_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('style_profiles', 'updated_at')
    op.drop_column('style_profiles', 'version')
    op.drop_column('style_profiles', 'profile_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('style_profiles', sa.Column('profile_json', sa.TEXT(), server_default=sa.text("'{}'"), nullable=False))
    op.add_column('style_profiles', sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), nullable=True))
    op.add_column('style_profiles', sa.Column('updated_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True))
    op.alter_column('style_profiles', 'novel_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('style_profiles', 'target_platform')
    op.drop_column('style_profiles', 'soul_statement')
    op.drop_column('style_profiles', 'central_question')
    op.drop_column('style_profiles', 'gap_rule')
    op.drop_column('style_profiles', 'rhythm_mode')
    op.drop_column('style_profiles', 'emotional_budget')
    op.drop_column('style_profiles', 'writer_voice')
    op.drop_column('style_profiles', 'genre')
    op.drop_column('style_profiles', 'id')
    op.add_column('novels', sa.Column('theme', sa.TEXT(), server_default=sa.text("'{}'"), nullable=True))
    op.add_column('novels', sa.Column('sub_genres', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True))
    op.add_column('novels', sa.Column('narrative_template', sa.TEXT(), server_default=sa.text("('')"), nullable=True))
    op.add_column('novels', sa.Column('reader_model', sa.TEXT(), server_default=sa.text("'{}'"), nullable=True))
    op.add_column('novels', sa.Column('information_plan', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True))
    op.add_column('novels', sa.Column('antagonist_system', sa.TEXT(), server_default=sa.text("'{}'"), nullable=True))
    op.alter_column('novels', 'current_arc',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'开篇'"))
    op.alter_column('novels', 'main_arc',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('novels', 'world_rules',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('novels', 'power_system',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('novels', 'world_geo',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('novels', 'world_era',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('novels', 'world_name',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('novels', 'synopsis',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('novels', 'id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('model_providers', sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=False))
    op.add_column('model_providers', sa.Column('updated_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=False))
    op.alter_column('model_providers', 'id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('factions', sa.Column('goal', sa.TEXT(), server_default=sa.text("('')"), nullable=True))
    op.add_column('factions', sa.Column('power_level', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
    op.add_column('factions', sa.Column('allies', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True))
    op.add_column('factions', sa.Column('resources', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True))
    op.add_column('factions', sa.Column('enemies', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True))
    op.add_column('factions', sa.Column('history', sa.TEXT(), server_default=sa.text("('')"), nullable=True))
    op.add_column('factions', sa.Column('internal_conflict', sa.TEXT(), server_default=sa.text("('')"), nullable=True))
    op.drop_constraint(None, 'factions', type_='foreignkey')
    op.create_foreign_key(None, 'factions', 'novels', ['novel_id'], ['id'])
    op.alter_column('factions', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('factions', 'leader',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('factions', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('factions', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('cost_logs', sa.Column('purpose', sa.TEXT(), server_default=sa.text("'generate'"), nullable=True))
    op.add_column('cost_logs', sa.Column('total_tokens', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
    op.add_column('cost_logs', sa.Column('duration_ms', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
    op.drop_constraint(None, 'cost_logs', type_='foreignkey')
    op.create_foreign_key(None, 'cost_logs', 'novels', ['novel_id'], ['id'])
    op.create_index(op.f('idx_cost_logs_novel'), 'cost_logs', ['novel_id'], unique=False)
    op.alter_column('cost_logs', 'created_at',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("(datetime('now'))"))
    op.alter_column('cost_logs', 'cost',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('cost_logs', 'completion_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('cost_logs', 'prompt_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('cost_logs', 'chapter_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cost_logs', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('characters', sa.Column('introduced_arc', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
    op.add_column('characters', sa.Column('foil_shared_trait', sa.TEXT(), server_default=sa.text("('')"), nullable=True))
    op.add_column('characters', sa.Column('goal', sa.TEXT(), server_default=sa.text("('')"), nullable=True))
    op.add_column('characters', sa.Column('lifecycle_status', sa.TEXT(), server_default=sa.text("'active'"), nullable=True))
    op.add_column('characters', sa.Column('voice_profile_json', sa.TEXT(), server_default=sa.text("'{}'"), nullable=True))
    op.add_column('characters', sa.Column('death_chapter', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
    op.add_column('characters', sa.Column('motivation', sa.TEXT(), server_default=sa.text("('')"), nullable=True))
    op.add_column('characters', sa.Column('arc', sa.TEXT(), server_default=sa.text("('')"), nullable=True))
    op.add_column('characters', sa.Column('foil_type', sa.TEXT(), server_default=sa.text("('')"), nullable=True))
    op.add_column('characters', sa.Column('death_impact', sa.TEXT(), server_default=sa.text("('')"), nullable=True))
    op.add_column('characters', sa.Column('wound', sa.TEXT(), server_default=sa.text("('')"), nullable=True))
    op.add_column('characters', sa.Column('foil_contrasting_trait', sa.TEXT(), server_default=sa.text("('')"), nullable=True))
    op.add_column('characters', sa.Column('foil_target', sa.TEXT(), server_default=sa.text("('')"), nullable=True))
    op.add_column('characters', sa.Column('last_appearance', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.create_foreign_key(None, 'characters', 'novels', ['novel_id'], ['id'])
    op.create_index(op.f('idx_characters_novel'), 'characters', ['novel_id'], unique=False)
    op.alter_column('characters', 'secrets',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('characters', 'power_level',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('characters', 'background',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('characters', 'personality',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('characters', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('character_relations', sa.Column('description', sa.TEXT(), server_default=sa.text("('')"), nullable=True))
    op.add_column('character_relations', sa.Column('relation', sa.TEXT(), nullable=False))
    op.add_column('character_relations', sa.Column('history', sa.TEXT(), server_default=sa.text("('')"), nullable=True))
    op.add_column('character_relations', sa.Column('char_1_id', sa.INTEGER(), nullable=False))
    op.add_column('character_relations', sa.Column('char_2_id', sa.INTEGER(), nullable=False))
    op.add_column('character_relations', sa.Column('key_moments', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True))
    op.add_column('character_relations', sa.Column('evolution_stages', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True))
    op.drop_constraint(None, 'character_relations', type_='foreignkey')
    op.create_foreign_key(None, 'character_relations', 'characters', ['char_2_id'], ['id'])
    op.create_foreign_key(None, 'character_relations', 'characters', ['char_1_id'], ['id'])
    op.create_foreign_key(None, 'character_relations', 'novels', ['novel_id'], ['id'])
    op.drop_constraint(None, 'character_relations', type_='unique')
    op.create_index(op.f('idx_relations_novel'), 'character_relations', ['novel_id'], unique=False)
    op.alter_column('character_relations', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('character_relations', 'relation_type')
    op.drop_column('character_relations', 'c2_name')
    op.drop_column('character_relations', 'c1_name')
    op.add_column('chapters', sa.Column('narrative_modes', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True))
    op.add_column('chapters', sa.Column('hook_type', sa.TEXT(), server_default=sa.text("('')"), nullable=True))
    op.add_column('chapters', sa.Column('scene_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
    op.add_column('chapters', sa.Column('plot_functions', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True))
    op.add_column('chapters', sa.Column('prompt_version', sa.TEXT(), server_default=sa.text("('')"), nullable=True))
    op.add_column('chapters', sa.Column('chapter_type', sa.TEXT(), server_default=sa.text("('')"), nullable=True))
    op.add_column('chapters', sa.Column('emotion', sa.TEXT(), server_default=sa.text("('')"), nullable=True))
    op.add_column('chapters', sa.Column('intensity', sa.INTEGER(), server_default=sa.text('5'), nullable=True))
    op.add_column('chapters', sa.Column('edit_ratio', sa.REAL(), server_default=sa.text('0'), nullable=True))
    op.drop_constraint(None, 'chapters', type_='foreignkey')
    op.create_foreign_key(None, 'chapters', 'novels', ['novel_id'], ['id'])
    op.create_index(op.f('idx_chapters_published'), 'chapters', ['novel_id', 'published_at'], unique=False)
    op.create_index(op.f('idx_chapters_novel'), 'chapters', ['novel_id'], unique=False)
    op.alter_column('chapters', 'generation_duration_ms',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('chapters', 'cost',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('chapters', 'completion_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('chapters', 'prompt_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('chapters', 'model_used',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('chapters', 'quality_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('chapters', 'revelations',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('chapters', 'key_events',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('chapters', 'ending_hook',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('chapters', 'content',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('chapters', 'summary',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('chapters', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'chapter_versions', type_='foreignkey')
    op.create_foreign_key(None, 'chapter_versions', 'chapters', ['chapter_id'], ['id'])
    op.create_index(op.f('idx_chapter_versions'), 'chapter_versions', ['chapter_id', 'version'], unique=False)
    op.alter_column('chapter_versions', 'created_at',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("(datetime('now'))"))
    op.alter_column('chapter_versions', 'reason',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('chapter_versions', 'version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('chapter_versions', 'word_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('chapter_versions', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'chapter_drafts', type_='foreignkey')
    op.create_foreign_key(None, 'chapter_drafts', 'chapters', ['chapter_id'], ['id'])
    op.create_index(op.f('idx_drafts_chapter'), 'chapter_drafts', ['chapter_id'], unique=False)
    op.alter_column('chapter_drafts', 'hook',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('chapter_drafts', 'preview',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('chapter_drafts', 'chapter_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chapter_drafts', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_table('chapter_fts',
    sa.Column('novel_id', sa.NullType(), nullable=True),
    sa.Column('chapter_num', sa.NullType(), nullable=True),
    sa.Column('title', sa.NullType(), nullable=True),
    sa.Column('summary', sa.NullType(), nullable=True)
    )
    op.create_table('reanchor_snapshots',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('novel_id', sa.TEXT(), nullable=False),
    sa.Column('trigger_chapter', sa.INTEGER(), nullable=False),
    sa.Column('world_snapshot', sa.TEXT(), nullable=False),
    sa.Column('chars_snapshot', sa.TEXT(), nullable=False),
    sa.Column('plot_snapshot', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id', 'trigger_chapter')
    )
    op.create_table('platform_auth',
    sa.Column('platform', sa.TEXT(), nullable=True),
    sa.Column('auth_data', sa.TEXT(), nullable=False),
    sa.Column('is_valid', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_verified_at', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('platform')
    )
    op.create_table('audio_progress',
    sa.Column('novel_id', sa.TEXT(), nullable=True),
    sa.Column('chapter_num', sa.INTEGER(), nullable=False),
    sa.Column('position_sec', sa.REAL(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('novel_id')
    )
    op.create_table('chapter_fts_content',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('c0', sa.NullType(), nullable=True),
    sa.Column('c1', sa.NullType(), nullable=True),
    sa.Column('c2', sa.NullType(), nullable=True),
    sa.Column('c3', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story_arcs',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('novel_id', sa.TEXT(), nullable=False),
    sa.Column('arc_name', sa.TEXT(), nullable=False),
    sa.Column('chapter_start', sa.INTEGER(), nullable=False),
    sa.Column('chapter_end', sa.INTEGER(), nullable=False),
    sa.Column('setting', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('new_characters_needed', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('power_ceiling', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('core_events', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('emotional_arc', sa.TEXT(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('stakes', sa.TEXT(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('hook_strategy', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('information_plan', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('summary', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_story_arcs_novel'), 'story_arcs', ['novel_id'], unique=False)
    op.create_table('audio_settings',
    sa.Column('key', sa.TEXT(), nullable=True),
    sa.Column('value', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('publish_records',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('chapter_id', sa.INTEGER(), nullable=False),
    sa.Column('platform', sa.TEXT(), nullable=False),
    sa.Column('success', sa.INTEGER(), server_default=sa.text('1'), nullable=False),
    sa.Column('url', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('error', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('screenshot_path', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_publish_records_ch'), 'publish_records', ['chapter_id'], unique=False)
    op.create_table('performance_logs',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('novel_id', sa.TEXT(), nullable=False),
    sa.Column('chapter_number', sa.INTEGER(), nullable=False),
    sa.Column('views', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('comments', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('collected_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_perf_novel'), 'performance_logs', ['novel_id', 'chapter_number'], unique=False)
    op.create_table('foreshadowing_tracker',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('novel_id', sa.TEXT(), nullable=False),
    sa.Column('created_chapter', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('hint_text', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('due_by_chapter', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('resolved_chapter', sa.INTEGER(), nullable=True),
    sa.Column('resolved_text', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('updated_at', sa.TEXT(), server_default=sa.text('("")'), nullable=True),
    sa.Column('chain_id', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('partial_payoffs', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('depends_on', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('misdirection', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.CheckConstraint("status IN ('active','resolved','overdue')"),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_foreshadowing_novel'), 'foreshadowing_tracker', ['novel_id', 'status'], unique=False)
    op.create_table('chapter_fts_idx',
    sa.Column('segid', sa.NullType(), nullable=False),
    sa.Column('term', sa.NullType(), nullable=False),
    sa.Column('pgno', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('segid', 'term')
    )
    op.create_table('story_timeline',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('novel_id', sa.TEXT(), nullable=False),
    sa.Column('chapter_num', sa.INTEGER(), nullable=False),
    sa.Column('absolute_time', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('relative_time', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('event_summary', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_timeline_novel'), 'story_timeline', ['novel_id', 'chapter_num'], unique=False)
    op.create_table('world_state',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('novel_id', sa.TEXT(), nullable=False),
    sa.Column('chapter_num', sa.INTEGER(), nullable=False),
    sa.Column('rule_name', sa.TEXT(), nullable=False),
    sa.Column('rule_description', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('is_broken', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('is_intentional', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_world_novel'), 'world_state', ['novel_id', 'chapter_num'], unique=False)
    op.create_table('character_voices',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('novel_id', sa.TEXT(), nullable=False),
    sa.Column('char_key', sa.TEXT(), nullable=False),
    sa.Column('voice_id', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('speed', sa.REAL(), server_default=sa.text('(1.0)'), nullable=False),
    sa.Column('pitch', sa.TEXT(), server_default=sa.text("'+0Hz'"), nullable=False),
    sa.Column('emotion_default', sa.TEXT(), server_default=sa.text("'calm'"), nullable=False),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('updated_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id', 'char_key')
    )
    op.create_table('subplots',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('novel_id', sa.TEXT(), nullable=False),
    sa.Column('subplot_type', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('characters', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('arc', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('progression_rule', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('merge_chapter', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'active'"), nullable=True),
    sa.Column('last_progressed_chapter', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.CheckConstraint("status IN ('active','merged','resolved')"),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_subplots_novel'), 'subplots', ['novel_id', 'status'], unique=False)
    op.create_table('character_state',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('novel_id', sa.TEXT(), nullable=False),
    sa.Column('chapter_num', sa.INTEGER(), nullable=False),
    sa.Column('char_name', sa.TEXT(), nullable=False),
    sa.Column('emotion', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('physical_state', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('knowledge', sa.TEXT(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('goal', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('location', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('relationships', sa.TEXT(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('notes', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('updated_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_char_state_novel'), 'character_state', ['novel_id', 'char_name', 'chapter_num'], unique=False)
    op.create_table('chapter_summaries',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('novel_id', sa.TEXT(), nullable=False),
    sa.Column('chapter_num', sa.INTEGER(), nullable=False),
    sa.Column('summary_text', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id', 'chapter_num')
    )
    op.create_index(op.f('idx_chapter_summaries_novel'), 'chapter_summaries', ['novel_id'], unique=False)
    op.create_table('audio_bookmarks',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('novel_id', sa.TEXT(), nullable=False),
    sa.Column('novel_title', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('chapter_num', sa.INTEGER(), nullable=False),
    sa.Column('chapter_title', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('position', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('note', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('tag', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storyboards',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('novel_id', sa.TEXT(), nullable=False),
    sa.Column('chapter_num', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('total_duration_sec', sa.REAL(), server_default=sa.text('0'), nullable=True),
    sa.Column('overall_mood', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('pacing', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('color_grade', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('music_theme', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('shots_json', sa.TEXT(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id', 'chapter_num')
    )
    op.create_table('unsaid_book',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('novel_id', sa.TEXT(), nullable=False),
    sa.Column('entry', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_unsaid_novel'), 'unsaid_book', ['novel_id'], unique=False)
    op.create_table('novel_tags',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('novel_id', sa.TEXT(), nullable=False),
    sa.Column('tag', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id', 'tag')
    )
    op.create_table('location_history',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('novel_id', sa.TEXT(), nullable=False),
    sa.Column('chapter_num', sa.INTEGER(), nullable=False),
    sa.Column('location_name', sa.TEXT(), nullable=False),
    sa.Column('event', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('state_change', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_location_novel'), 'location_history', ['novel_id', 'chapter_num'], unique=False)
    op.create_table('chapter_embeddings',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('chapter_id', sa.INTEGER(), nullable=False),
    sa.Column('chunk_index', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('chunk_text', sa.TEXT(), nullable=False),
    sa.Column('embedding', sa.TEXT(), nullable=False),
    sa.Column('model', sa.TEXT(), server_default=sa.text("'text-embedding-3-small'"), nullable=False),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id', 'chunk_index')
    )
    op.create_index(op.f('idx_embeddings_chapter'), 'chapter_embeddings', ['chapter_id'], unique=False)
    op.create_table('audio_playlist',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('novel_id', sa.TEXT(), nullable=False),
    sa.Column('novel_title', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('chapter_num', sa.INTEGER(), nullable=False),
    sa.Column('chapter_title', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('sort_order', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter_fts_data',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('block', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('world_evolution',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('novel_id', sa.TEXT(), nullable=False),
    sa.Column('chapter', sa.INTEGER(), nullable=False),
    sa.Column('change_type', sa.TEXT(), nullable=False),
    sa.Column('target', sa.TEXT(), nullable=False),
    sa.Column('change_desc', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_world_evo_novel'), 'world_evolution', ['novel_id', 'chapter'], unique=False)
    op.create_table('consistency_log',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('novel_id', sa.TEXT(), nullable=False),
    sa.Column('chapter_num', sa.INTEGER(), nullable=False),
    sa.Column('check_type', sa.TEXT(), server_default=sa.text("'character'"), nullable=False),
    sa.Column('severity', sa.TEXT(), server_default=sa.text("'warning'"), nullable=False),
    sa.Column('description', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('fix_suggestion', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('was_fixed', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.CheckConstraint("severity IN ('error','warning','info')"),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_consistency_novel'), 'consistency_log', ['novel_id', 'chapter_num'], unique=False)
    op.create_table('audio_stats',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('stat_key', sa.TEXT(), nullable=False),
    sa.Column('stat_value', sa.TEXT(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('updated_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stat_key')
    )
    op.create_table('voice_profile',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('novel_id', sa.TEXT(), nullable=False),
    sa.Column('chapter_num', sa.INTEGER(), nullable=False),
    sa.Column('before_text', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('after_text', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_voice_novel'), 'voice_profile', ['novel_id'], unique=False)
    op.create_table('chapter_fts_docsize',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('sz', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_logs',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('novel_id', sa.TEXT(), nullable=True),
    sa.Column('event', sa.TEXT(), nullable=False),
    sa.Column('detail', sa.TEXT(), server_default=sa.text("'{}'"), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_run_logs_time'), 'run_logs', ['created_at'], unique=False)
    op.create_index(op.f('idx_run_logs_novel'), 'run_logs', ['novel_id', 'event'], unique=False)
    op.create_table('visual_characters',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('novel_id', sa.TEXT(), nullable=False),
    sa.Column('char_key', sa.TEXT(), nullable=False),
    sa.Column('appearance', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('default_expression', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('signature_pose', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('color_palette', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('costume', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('injury_marks', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('voice_character', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('reference_images', sa.TEXT(), server_default=sa.text("'[]'"), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('updated_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id', 'char_key')
    )
    op.create_table('chapter_fts_config',
    sa.Column('k', sa.NullType(), nullable=False),
    sa.Column('v', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('k')
    )
    op.create_table('scheduler_state',
    sa.Column('novel_id', sa.TEXT(), nullable=True),
    sa.Column('is_running', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('next_run_at', sa.TEXT(), nullable=True),
    sa.Column('last_run_at', sa.TEXT(), nullable=True),
    sa.Column('last_result', sa.TEXT(), server_default=sa.text("('')"), nullable=True),
    sa.Column('consecutive_failures', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.CheckConstraint("last_result IN ('','success','failed','skipped')"),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('novel_id')
    )
    op.create_table('cost_ledger',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('novel_id', sa.TEXT(), nullable=False),
    sa.Column('chapter_num', sa.INTEGER(), nullable=False),
    sa.Column('character_name', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('gain', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('loss', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('gain_type', sa.TEXT(), server_default=sa.text("'info'"), nullable=False),
    sa.Column('loss_type', sa.TEXT(), server_default=sa.text("'none'"), nullable=False),
    sa.Column('is_immediate', sa.INTEGER(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_cost_novel'), 'cost_ledger', ['novel_id', 'chapter_num'], unique=False)
    op.create_table('plot_points',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('novel_id', sa.TEXT(), nullable=False),
    sa.Column('type', sa.TEXT(), server_default=sa.text("'plot'"), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('is_resolved', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('resolved_at', sa.TEXT(), nullable=True),
    sa.Column('sort_order', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.CheckConstraint("type IN ('plot','foreshadowing')"),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_plot_points_novel'), 'plot_points', ['novel_id', 'type', 'is_resolved'], unique=False)
    op.create_table('film_settings',
    sa.Column('key', sa.TEXT(), nullable=True),
    sa.Column('value', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###
